name: Sonarcloud reporting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shoppingflux/php:7.4-fpm
      env:
        COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create build directory
        run: mkdir build

      - name: PHPUnit with code coverage
        run: vendor/bin/phpunit --coverage-clover=build/clover.xml --log-junit=build/junit.xml

      - name: Fix clover report paths
        working-directory: ./build
        run: sed -i "s/__w\/$REPO_NAME\/$REPO_NAME/github\/workspace/" clover.xml
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
